Lacromis/Areas/Siuuu/Controllers/GarbageController.cs
using Lacromis.DAL;
using Lacromis.ExMethods;
using Lacromis.Models;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace Lacromis.Areas.Siuuu.Controllers
{
    [Area("Siuuu")]
    public class GarbageController : Controller
    {
        private AppDbContext _context;
        private IWebHostEnvironment _env;

        public GarbageController(AppDbContext context,IWebHostEnvironment env)
        {
            _context = context;
            _env = env;

        }
        public IActionResult Index()
        {
         List<Garbage> garbage = _context.garbages.ToList();

            return View(garbage);
        }
        public IActionResult Create()
        {
            ViewBag.catagory = new SelectList(_context.catagories.ToList(), "Id", "Name");

            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Garbage garbage)
        {

            ViewBag.catagory = new SelectList(_context.catagories.ToList(), "Id", "Name");

            if (garbage.Photo != null)
            {
                if (!(garbage.Photo.CheckSize(5)))
                {
                    ModelState.AddModelError("Photo", "5 mb limitinizi kecibsiz");
                    return View();


                }
                if (!(garbage.Photo.CheckType("image/")))
                {
                    ModelState.AddModelError("Photo", "img  formatinda bir seyler at");
                    return View();

                }


                garbage.ImgUrl = await garbage.Photo.SaveFileAsync(Path.Combine(_env.WebRootPath, "assets", "images", "icon"));


            }
            else
            {
                ModelState.AddModelError("Photo", "image elave etmelisen bos kecile bilmez");
                return View();
            }
            garbage.Count = 99;
            _context.garbages.Add(garbage);
            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }

        public IActionResult Update(int Id)
        {
            ViewBag.catagoryy = _context.catagories.ToList();

            Garbage product = _context.garbages.Find(Id);
            if (product == null)
            {
                return BadRequest();

            }
            return View(product);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(Garbage product, int Id)
        {

            if (Id != product.Id)
            {
                return NotFound();

            }
            Garbage product1 = _context.garbages.Find(Id);
            if (product1 == null)
            {
                return BadRequest();

            }

            if (!ModelState.IsValid)
            {
                return View();

            }








            if (product.Photo != null)
            {
                if (!(product.Photo.CheckSize(5)))
                {
                    ModelState.AddModelError("Photo", "5 mb limitinizi kecibsiz");
                    return View();


                }
                if (!(product.Photo.CheckType("image/")))
                {
                    ModelState.AddModelError("Photo", "img  formatinda bir seyler at");
                    return View();

                }

                string suloysu = Path.Combine(_env.WebRootPath, "assets", "images","icon", product1.ImgUrl);
                if (System.IO.File.Exists(suloysu))
                {
                    System.IO.File.Delete(suloysu);

                }

                product1.ImgUrl = await product.Photo.SaveFileAsync(Path.Combine(_env.WebRootPath, "assets", "images","icon"));


            }
            else
            {
                ModelState.AddModelError("Photo", "image elave etmelisen bos kecile bilmez");
                return View();
            }
            product1.Description = product.Description;
            product1.Descrition2 = product.Descrition2;
            product1.Descrition3 = product.Descrition3;
            product1.Price = product.Price;
            product1.Name = product.Name;

            _context.SaveChanges();

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Delete(int Id)
        {
            Garbage product = _context.garbages.Find(Id);
            if (product == null)
            {
                return BadRequest();

            }

            string suloysu = Path.Combine(_env.WebRootPath, "Assets", "images","icon", product.ImgUrl);
            if (System.IO.File.Exists(suloysu))
            {
                System.IO.File.Delete(suloysu);

            }
            _context.garbages.Remove(product);
            _context.SaveChanges();
            return RedirectToAction(nameof(Index));
        }
    }
}

Lacromis/Controllers/MetalController.cs
using Lacromis.DAL;
using Lacromis.Models;
using Lacromis.ViewModel;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lacromis.Controllers
{
    public class MetalController : Controller
    {
        private AppDbContext _context;

        public MetalController(AppDbContext context)
        {
            _context = context;

        }
        public IActionResult Index()
        {
            List<Metal> metal=_context.metals.ToList();
            return View(metal);
        }
        public IActionResult AddBasket(int? Id)
        {
            if (Id == null)
            {
                return BadRequest();

            }
            Metal buyProduct1 = _context.metals.Find(Id);
            if (buyProduct1 == null)
            {
                return NotFound();

            }

            List<BuyProductCount> buyProducts;
            string siu = Request.Cookies["basket"];
            if (siu == null)
            {
                buyProducts = new List<BuyProductCount>();

            }
            else
            {
                buyProducts = JsonConvert.DeserializeObject<List<BuyProductCount>>(Request.Cookies["basket"]);
            }
            BuyProductCount buyProductCount = buyProducts.FirstOrDefault(X => X.Id == buyProduct1.Id);
            if (buyProductCount == null)
            {
                BuyProductCount buyProductCount1 = new BuyProductCount();
                buyProductCount1.Id = buyProduct1.Id;
                buyProductCount1.Name = buyProduct1.Name;
                buyProductCount1.Count = 1;
                buyProducts.Add(buyProductCount1);

            }
            else
            {
                buyProductCount.Count++;
            }
            Response.Cookies.Append("basket", JsonConvert.SerializeObject(buyProducts), new CookieOptions { MaxAge = TimeSpan.FromMinutes(20) });
            return RedirectToAction(nameof(Index));
        }
        public IActionResult Basket()
        {
            List<BuyProductCount> buyProduct = JsonConvert.DeserializeObject<List<BuyProductCount>>(Request.Cookies["basket"]);
            List<BuyProductCount> updatedProducts = new List<BuyProductCount>();

            foreach (var item in buyProduct)
            {
                Metal dbProduct = _context.metals.FirstOrDefault(p => p.Id == item.Id);
                BuyProductCount basketProduct = new BuyProductCount()
                {
                    Id = dbProduct.Id,
                    Price = dbProduct.Price,
                    Name = dbProduct.Name,
                    Count = item.Count

                };

                basketProduct.Price = basketProduct.Price * basketProduct.Count;


                updatedProducts.Add(basketProduct);

            }

            return View(updatedProducts);
        }
        public async Task<IActionResult> InvokeAsync()
        {
            List<BuyProductCount> products = JsonConvert.DeserializeObject<List<BuyProductCount>>(Request.Cookies["basket"]);
            int cem = 0;
            foreach (var item in products)
            {
                cem += cem;

            }
            ViewBag.kount = cem;

            return View(await Task.FromResult(products));
        }
        public IActionResult RemoveItem(int? id)
        {
            if (id == null) return NotFound();

            string basket = Request.Cookies["basket"];

            List<BuyProductCount> products = JsonConvert.DeserializeObject<List<BuyProductCount>>(basket);

            BuyProductCount existProduct = products.FirstOrDefault(p => p.Id == id);

            if (existProduct == null) return NotFound();

            products.Remove(existProduct);

            Response.Cookies.Append(
                "basket",
                JsonConvert.SerializeObject(products),
                new CookieOptions { MaxAge = TimeSpan.FromMinutes(20) }
                );

            return RedirectToAction(nameof(Basket));
        }

        public IActionResult Topla(int? id)
        {
            if (id == null) return NotFound();

            string basket = Request.Cookies["basket"];

            List<BuyProductCount> products = JsonConvert.DeserializeObject<List<BuyProductCount>>(basket);

            BuyProductCount existProduct = products.FirstOrDefault(p => p.Id == id);

            if (existProduct == null) return NotFound();

            Metal dbProdut = _context.metals.FirstOrDefault(p => p.Id == id);

            if (dbProdut.Count > existProduct.Count)
            {
                existProduct.Count++;
            }
            else
            {
                TempData["Fail"] = "not enough count";
                return RedirectToAction("Basket", "Basket");
            }

            Response.Cookies.Append(
                "basket",
                JsonConvert.SerializeObject(products),
                new CookieOptions { MaxAge = TimeSpan.FromMinutes(20) }
                );

            return RedirectToAction(nameof(Basket));
        }

        public IActionResult Cix(int? id)
        {
            if (id == null) return NotFound();

            string basket = Request.Cookies["basket"];

            List<BuyProductCount> products = JsonConvert.DeserializeObject<List<BuyProductCount>>(basket);

            BuyProductCount existProduct = products.FirstOrDefault(p => p.Id == id);

            if (existProduct == null) return NotFound();

            if (existProduct.Count > 1)
            {
                existProduct.Count--;
            }
            else
            {
                RemoveItem(existProduct.Id);

                return RedirectToAction(nameof(Basket));
            }


            Response.Cookies.Append(
                "basket",
                JsonConvert.SerializeObject(products),
                new CookieOptions { MaxAge = TimeSpan.FromMinutes(20) }
                );

            return RedirectToAction(nameof(Basket));
        }

    }


}

Lacromis/Areas/Siuuu/Views/Shared/_AdminLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="~/Admin/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Interface
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo"
                    aria-expanded="true" aria-controls="collapseTwo">
                    <i class="fas fa-fw fa-cog"></i>
                    <span>Create Garbage</span>
                </a>
                <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Components:</h6>
                        <a class="collapse-item" asp-action="Index" asp-area="Siuuu" asp-controller="Garbage">View Garbage</a>
                        <a class="collapse-item" asp-action="Create" asp-area="Siuuu" asp-controller="Garbage">CREATE GARBAGE </a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Utilities Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities"
                    aria-expanded="true" aria-controls="collapseUtilities">
                    <i class="fas fa-fw fa-wrench"></i>
                    <span>Metal</span>
                </a>
                <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities"
                    data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Custom Utilities:</h6>
                        <a class="collapse-item" asp-action="Index" asp-area="Siuuu" asp-controller="Metal">View Metal</a>
                        <a class="collapse-item" asp-action="Create" asp-area="Siuuu" asp-controller="Metal">Create Metal</a>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Addons
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                    aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-folder"></i>
                    <span>Pages</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <h6 class="collapse-header">Login Screens:</h6>
                        <a class="collapse-item" href="login.html">Login</a>
                        <a class="collapse-item" href="register.html">Register</a>
                        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
                        <div class="collapse-divider"></div>
                        <h6 class="collapse-header">Other Pages:</h6>
                        <a class="collapse-item" href="404.html">404 Page</a>
                        <a class="collapse-item" href="blank.html">Blank Page</a>
                    </div>
                </div>
            </li>

            <!-- Nav Item - Charts -->
            <li class="nav-item">
                <a class="nav-link" href="charts.html">
                    <i class="fas fa-fw fa-chart-area"></i>
                    <span>Charts</span></a>
            </li>

            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-table"></i>
                    <span>Tables</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

            <!-- Sidebar Message -->
            <div class="sidebar-card d-none d-lg-flex">
                <img class="sidebar-card-illustration mb-2" src="~/Admin/img/undraw_rocket.svg" alt="...">
                <p class="text-center mb-2"><strong>SB Admin Pro</strong> is packed with premium features, components, and more!</p>
                <a class="btn btn-success btn-sm" href="https://startbootstrap.com/theme/sb-admin-pro">Upgrade to Pro!</a>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <!-- End of Main Content -->
            @RenderBody()
            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="~/Admin/vendor/jquery/jquery.min.js"></script>
    <script src="~/Admin/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="~/Admin/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="~/Admin/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="~/Admin/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="~/Admin/js/demo/chart-area-demo.js"></script>
    <script src="~/Admin/js/demo/chart-pie-demo.js"></script>

</body>

</html>